export const PRODUCT_CATEGORIES = {
  MENS_CLOTHING: "MENS_CLOTHING",
  WOMEN_CLOTHING: "WOMEN_CLOTHING",
};

export const DISPLAY_CATEGORIES = {
  MENS_CLOTHING: "MENS_CLOTHING",
  WOMEN_CLOTHING: "WOMEN_CLOTHING",
  UNAVAILABLE: "UNAVAILABLE",
};
