export const PRODUCT_CATEGORIES = {
  MENS_CLOTHING: "men's clothing",
  WOMENS_CLOTHING: "women's clothing",
};

export const DISPLAY_CATEGORIES = {
  MENS_CLOTHING: "MENS_CLOTHING",
  WOMENS_CLOTHING: "WOMENS_CLOTHING",
  UNAVAILABLE: "UNAVAILABLE",
};
